//! Convert vz-stack [`ServiceSpec`] into vz-oci [`RunConfig`].
//!
//! This is the bridge between the stack control plane (typed specs) and
//! the OCI runtime (container execution). Each field is mapped with
//! explicit semantics documented per conversion function.

use std::path::PathBuf;

use crate::error::StackError;
use crate::spec::{PortSpec, ResourcesSpec, ServiceSecretRef, ServiceSpec};
use crate::volume::ResolvedMount;

/// Convert a [`ServiceSpec`] into a vz-oci [`RunConfig`].
///
/// Mounts must be pre-resolved via [`crate::resolve_mounts`] because
/// named volumes need a concrete host directory. Port mappings with
/// `host_port: None` are assigned the container port as the host port
/// (real allocation deferred to a later bead).
///
/// `secret_mounts` are additional bind mounts for staged secret files,
/// generated by the executor after reading and staging secret contents.
pub fn service_to_run_config(
    spec: &ServiceSpec,
    resolved_mounts: &[ResolvedMount],
    secret_mounts: &[vz_runtime_contract::MountSpec],
) -> Result<vz_runtime_contract::RunConfig, StackError> {
    let cmd = build_cmd(spec);
    let env = convert_env(&spec.environment);
    let ports = convert_ports(&spec.ports)?;
    let mut mounts = convert_mounts(resolved_mounts);
    mounts.extend_from_slice(secret_mounts);
    let resources = convert_resources(&spec.resources);

    // Convert labels to OCI annotations.
    let oci_annotations: Vec<(String, String)> = spec
        .labels
        .iter()
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();

    // Convert sysctls from HashMap to Vec.
    let sysctls: Vec<(String, String)> = spec
        .sysctls
        .iter()
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();

    // Convert ulimits from UlimitSpec to tuple form.
    let ulimits: Vec<(String, u64, u64)> = spec
        .ulimits
        .iter()
        .map(|u| (u.name.clone(), u.soft, u.hard))
        .collect();

    Ok(vz_runtime_contract::RunConfig {
        cmd,
        working_dir: spec.working_dir.clone(),
        env,
        user: spec.user.clone(),
        ports,
        mounts,
        cpus: resources.cpus,
        memory_mb: resources.memory_mb,
        cpu_quota: resources.cpu_quota,
        cpu_period: resources.cpu_period,
        // Stack containers should have networking for inter-service communication.
        network_enabled: Some(true),
        extra_hosts: spec.extra_hosts.clone(),
        // Capture container stdout/stderr to log files for `vz stack logs`.
        capture_logs: true,
        // Security fields
        cap_add: spec.cap_add.clone(),
        cap_drop: spec.cap_drop.clone(),
        privileged: spec.privileged,
        read_only_rootfs: spec.read_only,
        sysctls,
        // Resource extensions
        ulimits,
        pids_limit: spec.resources.pids_limit,
        // Container identity
        hostname: spec.hostname.clone(),
        domainname: spec.domainname.clone(),
        oci_annotations,
        // Stop lifecycle
        stop_signal: spec.stop_signal.clone(),
        stop_grace_period_secs: spec.stop_grace_period_secs,
        // Remaining fields use defaults; future beads may populate them.
        ..Default::default()
    })
}

/// Convert service secret references into bind mount specs.
///
/// Each secret ref produces a read-only bind mount from the staged secret
/// file on the host to `/run/secrets/<target>` inside the container.
/// The `staged_dir` should point to the directory where the executor has
/// staged the secret file contents (e.g., `<data_dir>/secrets/<stack_name>/`).
#[allow(dead_code)] // Used by executor secrets staging (in progress)
pub fn secrets_to_mounts(
    secrets: &[ServiceSecretRef],
    staged_dir: &std::path::Path,
) -> Vec<vz_runtime_contract::MountSpec> {
    secrets
        .iter()
        .map(|s| vz_runtime_contract::MountSpec {
            source: Some(staged_dir.join(&s.source)),
            target: PathBuf::from(format!("/run/secrets/{}", s.target)),
            mount_type: vz_runtime_contract::MountType::Bind,
            access: vz_runtime_contract::MountAccess::ReadOnly,
            subpath: None,
        })
        .collect()
}

/// Build the command vector from entrypoint and command overrides.
///
/// If both entrypoint and command are set, they are concatenated
/// (entrypoint as the process, command as arguments) — matching
/// Docker/OCI semantics.
fn build_cmd(spec: &ServiceSpec) -> Vec<String> {
    match (&spec.entrypoint, &spec.command) {
        (Some(ep), Some(cmd)) => {
            let mut full = ep.clone();
            full.extend(cmd.iter().cloned());
            full
        }
        (Some(ep), None) => ep.clone(),
        (None, Some(cmd)) => cmd.clone(),
        (None, None) => Vec::new(),
    }
}

/// Convert a `HashMap<String, String>` environment into the
/// `Vec<(String, String)>` format used by vz-oci.
///
/// Keys are sorted for deterministic output.
fn convert_env(env: &std::collections::HashMap<String, String>) -> Vec<(String, String)> {
    let mut pairs: Vec<(String, String)> =
        env.iter().map(|(k, v)| (k.clone(), v.clone())).collect();
    pairs.sort_by(|a, b| a.0.cmp(&b.0));
    pairs
}

/// Convert stack [`PortSpec`] entries to vz-oci [`PortMapping`] entries.
///
/// When `host_port` is `None`, the container port is used as the host
/// port (a simple default; real dynamic allocation is a later bead).
fn convert_ports(ports: &[PortSpec]) -> Result<Vec<vz_runtime_contract::PortMapping>, StackError> {
    let mut mappings = Vec::with_capacity(ports.len());
    for port in ports {
        let protocol = match port.protocol.as_str() {
            "tcp" => vz_runtime_contract::PortProtocol::Tcp,
            "udp" => vz_runtime_contract::PortProtocol::Udp,
            other => {
                return Err(StackError::InvalidSpec(format!(
                    "unsupported port protocol '{other}'"
                )));
            }
        };
        mappings.push(vz_runtime_contract::PortMapping {
            host: port.host_port.unwrap_or(port.container_port),
            container: port.container_port,
            protocol,
            target_host: None,
        });
    }
    Ok(mappings)
}

/// Convert pre-resolved mounts into vz-oci [`MountSpec`] entries.
fn convert_mounts(resolved: &[ResolvedMount]) -> Vec<vz_runtime_contract::MountSpec> {
    resolved
        .iter()
        .map(|rm| {
            let (mount_type, source) = match &rm.kind {
                crate::volume::ResolvedMountKind::Bind => {
                    (vz_runtime_contract::MountType::Bind, rm.host_path.clone())
                }
                crate::volume::ResolvedMountKind::Named { volume_name } => {
                    // Named volumes are backed by a persistent ext4 disk image
                    // attached to the VM. Data lives at `/run/vz-oci/volumes/{name}`
                    // on the block device and survives across stack restarts.
                    (
                        vz_runtime_contract::MountType::Volume {
                            volume_name: volume_name.clone(),
                        },
                        None,
                    )
                }
                crate::volume::ResolvedMountKind::Ephemeral => {
                    (vz_runtime_contract::MountType::Tmpfs, None)
                }
            };

            let access = if rm.read_only {
                vz_runtime_contract::MountAccess::ReadOnly
            } else {
                vz_runtime_contract::MountAccess::ReadWrite
            };

            vz_runtime_contract::MountSpec {
                source,
                target: PathBuf::from(&rm.target),
                mount_type,
                access,
                subpath: rm.subpath.clone(),
            }
        })
        .collect()
}

/// CFS period in microseconds (100ms).
const CFS_PERIOD_US: u64 = 100_000;

/// Converted resource values for vz-oci RunConfig.
struct ConvertedResources {
    cpus: Option<u8>,
    memory_mb: Option<u64>,
    cpu_quota: Option<i64>,
    cpu_period: Option<u64>,
}

/// Convert typed resource constraints into vz-oci CPU/memory fields.
///
/// CPU: fractional cores → VM cpus (ceiling) + cgroup quota/period.
///   e.g., 0.5 → cpus=1, quota=50000, period=100000
///   e.g., 2.0 → cpus=2, quota=200000, period=100000
/// Memory: bytes → megabytes.
fn convert_resources(resources: &ResourcesSpec) -> ConvertedResources {
    let cpus = resources.cpus.map(|c| {
        let rounded = c.ceil() as u8;
        if rounded == 0 { 1 } else { rounded }
    });

    let memory_mb = resources.memory_bytes.map(|bytes| bytes / (1024 * 1024));

    let (cpu_quota, cpu_period) = if let Some(c) = resources.cpus {
        let quota = (c * CFS_PERIOD_US as f64) as i64;
        (Some(quota), Some(CFS_PERIOD_US))
    } else {
        (None, None)
    };

    ConvertedResources {
        cpus,
        memory_mb,
        cpu_quota,
        cpu_period,
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;
    use crate::spec::{
        HealthCheckSpec, MountSpec as StackMountSpec, RestartPolicy, ServiceDependency,
    };
    use crate::volume::{ResolvedMount, ResolvedMountKind};
    use std::collections::HashMap;

    fn minimal_service() -> ServiceSpec {
        ServiceSpec {
            name: "web".to_string(),
            image: "nginx:latest".to_string(),
            command: None,
            entrypoint: None,
            environment: HashMap::new(),
            working_dir: None,
            user: None,
            mounts: vec![],
            ports: vec![],
            depends_on: vec![],
            healthcheck: None,
            restart_policy: None,
            resources: ResourcesSpec::default(),
            extra_hosts: vec![],
            secrets: vec![],
            networks: vec![],
            cap_add: vec![],
            cap_drop: vec![],
            privileged: false,
            read_only: false,
            sysctls: HashMap::new(),
            ulimits: vec![],
            container_name: None,
            hostname: None,
            domainname: None,
            labels: HashMap::new(),
            stop_signal: None,
            stop_grace_period_secs: None,
        }
    }

    #[test]
    fn minimal_service_converts() {
        let spec = minimal_service();
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert!(config.cmd.is_empty());
        assert!(config.env.is_empty());
        assert!(config.ports.is_empty());
        assert!(config.mounts.is_empty());
        assert_eq!(config.working_dir, None);
        assert_eq!(config.user, None);
        assert_eq!(config.cpus, None);
        assert_eq!(config.memory_mb, None);
        assert_eq!(config.network_enabled, Some(true));
        assert!(config.capture_logs, "stack containers must capture logs");
    }

    #[test]
    fn command_only() {
        let mut spec = minimal_service();
        spec.command = Some(vec!["echo".to_string(), "hello".to_string()]);
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.cmd, vec!["echo", "hello"]);
    }

    #[test]
    fn entrypoint_only() {
        let mut spec = minimal_service();
        spec.entrypoint = Some(vec!["/bin/sh".to_string()]);
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.cmd, vec!["/bin/sh"]);
    }

    #[test]
    fn entrypoint_plus_command() {
        let mut spec = minimal_service();
        spec.entrypoint = Some(vec!["/bin/sh".to_string(), "-c".to_string()]);
        spec.command = Some(vec!["echo hi".to_string()]);
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.cmd, vec!["/bin/sh", "-c", "echo hi"]);
    }

    #[test]
    fn environment_sorted() {
        let mut spec = minimal_service();
        spec.environment = HashMap::from([
            ("ZZZ".to_string(), "last".to_string()),
            ("AAA".to_string(), "first".to_string()),
            ("MMM".to_string(), "middle".to_string()),
        ]);
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.env[0], ("AAA".to_string(), "first".to_string()));
        assert_eq!(config.env[1], ("MMM".to_string(), "middle".to_string()));
        assert_eq!(config.env[2], ("ZZZ".to_string(), "last".to_string()));
    }

    #[test]
    fn working_dir_and_user() {
        let mut spec = minimal_service();
        spec.working_dir = Some("/app".to_string());
        spec.user = Some("1000:1000".to_string());
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.working_dir, Some("/app".to_string()));
        assert_eq!(config.user, Some("1000:1000".to_string()));
    }

    #[test]
    fn port_tcp_with_host() {
        let mut spec = minimal_service();
        spec.ports = vec![PortSpec {
            protocol: "tcp".to_string(),
            container_port: 80,
            host_port: Some(8080),
        }];
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.ports.len(), 1);
        assert_eq!(config.ports[0].host, 8080);
        assert_eq!(config.ports[0].container, 80);
        assert_eq!(
            config.ports[0].protocol,
            vz_runtime_contract::PortProtocol::Tcp
        );
    }

    #[test]
    fn port_udp() {
        let mut spec = minimal_service();
        spec.ports = vec![PortSpec {
            protocol: "udp".to_string(),
            container_port: 53,
            host_port: Some(5353),
        }];
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(
            config.ports[0].protocol,
            vz_runtime_contract::PortProtocol::Udp
        );
    }

    #[test]
    fn port_no_host_defaults_to_container() {
        let mut spec = minimal_service();
        spec.ports = vec![PortSpec {
            protocol: "tcp".to_string(),
            container_port: 3000,
            host_port: None,
        }];
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.ports[0].host, 3000);
    }

    #[test]
    fn port_invalid_protocol() {
        let mut spec = minimal_service();
        spec.ports = vec![PortSpec {
            protocol: "sctp".to_string(),
            container_port: 80,
            host_port: Some(80),
        }];
        let err = service_to_run_config(&spec, &[], &[]).unwrap_err();
        assert!(matches!(err, StackError::InvalidSpec(_)));
    }

    #[test]
    fn bind_mount_converts() {
        let resolved = vec![ResolvedMount {
            host_path: Some(PathBuf::from("/host/data")),
            target: "/container/data".to_string(),
            read_only: true,
            kind: ResolvedMountKind::Bind,
            subpath: None,
        }];
        let spec = minimal_service();
        let config = service_to_run_config(&spec, &resolved, &[]).unwrap();
        assert_eq!(config.mounts.len(), 1);
        assert_eq!(config.mounts[0].source, Some(PathBuf::from("/host/data")));
        assert_eq!(config.mounts[0].target, PathBuf::from("/container/data"));
        assert_eq!(
            config.mounts[0].mount_type,
            vz_runtime_contract::MountType::Bind
        );
        assert_eq!(
            config.mounts[0].access,
            vz_runtime_contract::MountAccess::ReadOnly
        );
    }

    #[test]
    fn named_volume_mount_converts_as_volume() {
        let resolved = vec![ResolvedMount {
            host_path: Some(PathBuf::from("/volumes/dbdata")),
            target: "/var/lib/db".to_string(),
            read_only: false,
            kind: ResolvedMountKind::Named {
                volume_name: "dbdata".to_string(),
            },
            subpath: None,
        }];
        let spec = minimal_service();
        let config = service_to_run_config(&spec, &resolved, &[]).unwrap();
        // Named volumes use a persistent ext4 disk image inside the VM.
        assert_eq!(
            config.mounts[0].mount_type,
            vz_runtime_contract::MountType::Volume {
                volume_name: "dbdata".to_string(),
            }
        );
        assert!(config.mounts[0].source.is_none());
    }

    #[test]
    fn ephemeral_mount_converts_as_tmpfs() {
        let resolved = vec![ResolvedMount {
            host_path: None,
            target: "/tmp".to_string(),
            read_only: false,
            kind: ResolvedMountKind::Ephemeral,
            subpath: None,
        }];
        let spec = minimal_service();
        let config = service_to_run_config(&spec, &resolved, &[]).unwrap();
        assert_eq!(
            config.mounts[0].mount_type,
            vz_runtime_contract::MountType::Tmpfs
        );
        assert!(config.mounts[0].source.is_none());
    }

    #[test]
    fn resources_cpu_and_memory() {
        let mut spec = minimal_service();
        spec.resources = ResourcesSpec {
            cpus: Some(4.0),
            memory_bytes: Some(1024 * 1024 * 1024), // 1 GiB
            ..Default::default()
        };
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.cpus, Some(4));
        assert_eq!(config.memory_mb, Some(1024));
        assert_eq!(config.cpu_quota, Some(400_000)); // 4.0 * 100_000
        assert_eq!(config.cpu_period, Some(100_000));
    }

    #[test]
    fn resources_memory_megabytes() {
        let mut spec = minimal_service();
        spec.resources = ResourcesSpec {
            cpus: None,
            memory_bytes: Some(512 * 1024 * 1024), // 512 MiB
            ..Default::default()
        };
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.memory_mb, Some(512));
    }

    #[test]
    fn resources_fractional_cpus_round_up() {
        let mut spec = minimal_service();
        spec.resources = ResourcesSpec {
            cpus: Some(0.5),
            memory_bytes: None,
            ..Default::default()
        };
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.cpus, Some(1)); // ceil(0.5) = 1
        assert_eq!(config.cpu_quota, Some(50_000)); // 0.5 * 100_000
        assert_eq!(config.cpu_period, Some(100_000));
    }

    #[test]
    fn extra_hosts_passed_through() {
        let mut spec = minimal_service();
        spec.extra_hosts = vec![
            ("db".to_string(), "127.0.0.1".to_string()),
            ("cache".to_string(), "10.0.0.5".to_string()),
        ];
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.extra_hosts.len(), 2);
        assert_eq!(
            config.extra_hosts[0],
            ("db".to_string(), "127.0.0.1".to_string())
        );
        assert_eq!(
            config.extra_hosts[1],
            ("cache".to_string(), "10.0.0.5".to_string())
        );
    }

    #[test]
    fn resources_zero_memory_bytes() {
        let mut spec = minimal_service();
        spec.resources = ResourcesSpec {
            cpus: None,
            memory_bytes: Some(0),
            ..Default::default()
        };
        let config = service_to_run_config(&spec, &[], &[]).unwrap();
        assert_eq!(config.memory_mb, Some(0));
    }

    #[test]
    fn full_service_converts() {
        let spec = ServiceSpec {
            name: "api".to_string(),
            image: "myapp:latest".to_string(),
            command: Some(vec!["serve".to_string()]),
            entrypoint: Some(vec!["/app/bin".to_string()]),
            environment: HashMap::from([
                ("PORT".to_string(), "3000".to_string()),
                ("ENV".to_string(), "production".to_string()),
            ]),
            working_dir: Some("/app".to_string()),
            user: Some("node".to_string()),
            mounts: vec![StackMountSpec::Bind {
                source: "/host/config".to_string(),
                target: "/config".to_string(),
                read_only: true,
            }],
            ports: vec![
                PortSpec {
                    protocol: "tcp".to_string(),
                    container_port: 3000,
                    host_port: Some(3000),
                },
                PortSpec {
                    protocol: "tcp".to_string(),
                    container_port: 9090,
                    host_port: None,
                },
            ],
            depends_on: vec![ServiceDependency::started("db")],
            healthcheck: Some(HealthCheckSpec {
                test: vec![
                    "CMD".to_string(),
                    "curl".to_string(),
                    "localhost:3000".to_string(),
                ],
                interval_secs: Some(30),
                timeout_secs: Some(5),
                retries: Some(3),
                start_period_secs: Some(10),
            }),
            restart_policy: Some(RestartPolicy::Always),
            resources: ResourcesSpec {
                cpus: Some(2.0),
                memory_bytes: Some(1024 * 1024 * 1024),
                reservation_cpus: None,
                reservation_memory_bytes: None,
                pids_limit: None,
            },
            extra_hosts: vec![],
            secrets: vec![],
            networks: vec![],
            cap_add: vec![],
            cap_drop: vec![],
            privileged: false,
            read_only: false,
            sysctls: HashMap::new(),
            ulimits: vec![],
            container_name: None,
            hostname: None,
            domainname: None,
            labels: HashMap::new(),
            stop_signal: None,
            stop_grace_period_secs: None,
        };

        let resolved_mounts = vec![ResolvedMount {
            host_path: Some(PathBuf::from("/host/config")),
            target: "/config".to_string(),
            read_only: true,
            kind: ResolvedMountKind::Bind,
            subpath: None,
        }];

        let config = service_to_run_config(&spec, &resolved_mounts, &[]).unwrap();
        assert_eq!(config.cmd, vec!["/app/bin", "serve"]);
        assert_eq!(config.env.len(), 2);
        assert_eq!(config.env[0], ("ENV".to_string(), "production".to_string()));
        assert_eq!(config.env[1], ("PORT".to_string(), "3000".to_string()));
        assert_eq!(config.working_dir, Some("/app".to_string()));
        assert_eq!(config.user, Some("node".to_string()));
        assert_eq!(config.ports.len(), 2);
        assert_eq!(config.ports[0].host, 3000);
        assert_eq!(config.ports[1].host, 9090); // defaults to container port
        assert_eq!(config.mounts.len(), 1);
        assert_eq!(config.cpus, Some(2));
        assert_eq!(config.memory_mb, Some(1024));
    }
}
