#![forbid(unsafe_code)]

use std::error::Error;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=src/openapi_doc.rs");
    if let Err(error) = generate_openapi_doc() {
        panic!("failed to generate OpenAPI registration: {error}");
    }
}

fn generate_openapi_doc() -> Result<(), Box<dyn Error>> {
    let source = fs::read_to_string("src/openapi_doc.rs")?;
    let schema_source = fs::read_to_string("src/lib.rs")?;
    let mut path_functions = Vec::new();
    let mut saw_path_attribute = false;
    let mut schema_types = Vec::new();
    let mut saw_schema_derive = false;
    let mut in_derive = false;
    let mut derive_mentions_to_schema = false;

    for line in source.lines() {
        let trimmed = line.trim();
        if trimmed
            .starts_with("include!(concat!(env!(\"OUT_DIR\"), \"/openapi_doc_generated.rs\"));")
        {
            break;
        }

        if trimmed.starts_with("#[utoipa::path(") {
            saw_path_attribute = true;
            continue;
        }

        if saw_path_attribute && trimmed.starts_with("fn ") {
            if let Some(function_name) = parse_function_name(trimmed) {
                path_functions.push(function_name.to_string());
            }
            saw_path_attribute = false;
        }
    }

    if path_functions.is_empty() {
        return Err("no #[utoipa::path] function declarations found".into());
    }

    for line in schema_source.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("#[derive(") {
            in_derive = true;
            derive_mentions_to_schema = trimmed.contains("ToSchema");
            if trimmed.ends_with(")]") {
                in_derive = false;
                saw_schema_derive = derive_mentions_to_schema;
                derive_mentions_to_schema = false;
            }
            continue;
        }

        if in_derive {
            derive_mentions_to_schema |= trimmed.contains("ToSchema");
            if trimmed.ends_with(")]") {
                in_derive = false;
                saw_schema_derive = derive_mentions_to_schema;
                derive_mentions_to_schema = false;
            }
            continue;
        }

        if !saw_schema_derive {
            continue;
        }

        if trimmed.starts_with("#[") {
            continue;
        }

        if let Some(type_name) = parse_type_name(trimmed) {
            if !schema_types.iter().any(|existing| existing == type_name) {
                schema_types.push(type_name.to_string());
            }
            saw_schema_derive = false;
            continue;
        }
    }

    if schema_types.is_empty() {
        return Err("no #[derive(..., ToSchema)] types found in src/lib.rs".into());
    }

    let mut generated = String::new();
    generated.push_str("// Auto-generated by build.rs. Do not edit manually.\n");
    generated.push_str("#[derive(OpenApi)]\n");
    generated.push_str("#[openapi(\n");
    generated.push_str("    info(\n");
    generated.push_str("        title = \"vz Runtime V2 API\",\n");
    generated.push_str("        version = \"2.0.0-alpha\",\n");
    generated.push_str("        description = API_DESCRIPTION\n");
    generated.push_str("    ),\n");
    generated.push_str("    paths(\n");
    for function in path_functions {
        generated.push_str("        ");
        generated.push_str(function.as_str());
        generated.push_str(",\n");
    }
    generated.push_str("    ),\n");
    generated.push_str("    components(schemas(\n");
    for schema in schema_types {
        generated.push_str("        ");
        generated.push_str("crate::");
        generated.push_str(schema.as_str());
        generated.push_str(",\n");
    }
    generated.push_str("    ))\n");
    generated.push_str(")]\n");
    generated.push_str("struct ApiDoc;\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);
    fs::write(out_dir.join("openapi_doc_generated.rs"), generated)?;
    Ok(())
}

fn parse_function_name(signature_line: &str) -> Option<&str> {
    let line = signature_line.strip_prefix("fn ")?;
    let name_end = line.find('(')?;
    Some(line[..name_end].trim())
}

fn parse_type_name(declaration_line: &str) -> Option<&str> {
    let line = declaration_line
        .strip_prefix("pub struct ")
        .or_else(|| declaration_line.strip_prefix("struct "))
        .or_else(|| declaration_line.strip_prefix("pub enum "))
        .or_else(|| declaration_line.strip_prefix("enum "))?;
    let end = line
        .find(|ch: char| ch == '<' || ch == '{' || ch == '(' || ch.is_whitespace())
        .unwrap_or(line.len());
    let name = line[..end].trim();
    if name.is_empty() { None } else { Some(name) }
}
