#![forbid(unsafe_code)]

use std::error::Error;
use std::fs;
use std::path::PathBuf;

const COMPONENT_SCHEMAS: &[&str] = &[
    "ErrorResponse",
    "CapabilitiesResponse",
    "ApiEventRecord",
    "EventsResponse",
    "CreateSandboxRequest",
    "SandboxPayload",
    "SandboxResponse",
    "SandboxListResponse",
    "OpenLeaseRequest",
    "LeasePayload",
    "LeaseResponse",
    "LeaseListResponse",
    "CreateExecutionRequest",
    "WriteExecStdinRequest",
    "ResizeExecRequest",
    "SignalExecRequest",
    "ExecutionPayload",
    "ExecutionResponse",
    "ExecutionListResponse",
    "CreateCheckpointRequest",
    "ForkCheckpointRequest",
    "CheckpointPayload",
    "CheckpointResponse",
    "RestoreCheckpointResponse",
    "CheckpointListResponse",
    "CreateContainerRequest",
    "ContainerPayload",
    "ContainerResponse",
    "ContainerListResponse",
    "ImagePayload",
    "ImageResponse",
    "ImageListResponse",
    "ReceiptPayload",
    "ReceiptResponse",
    "StartBuildRequest",
    "BuildPayload",
    "BuildResponse",
    "BuildListResponse",
];

fn main() {
    println!("cargo:rerun-if-changed=src/openapi_doc.rs");
    if let Err(error) = generate_openapi_doc() {
        panic!("failed to generate OpenAPI registration: {error}");
    }
}

fn generate_openapi_doc() -> Result<(), Box<dyn Error>> {
    let source = fs::read_to_string("src/openapi_doc.rs")?;
    let mut path_functions = Vec::new();
    let mut saw_path_attribute = false;

    for line in source.lines() {
        let trimmed = line.trim();
        if trimmed
            .starts_with("include!(concat!(env!(\"OUT_DIR\"), \"/openapi_doc_generated.rs\"));")
        {
            break;
        }

        if trimmed.starts_with("#[utoipa::path(") {
            saw_path_attribute = true;
            continue;
        }

        if saw_path_attribute && trimmed.starts_with("fn ") {
            if let Some(function_name) = parse_function_name(trimmed) {
                path_functions.push(function_name.to_string());
            }
            saw_path_attribute = false;
        }
    }

    if path_functions.is_empty() {
        return Err("no #[utoipa::path] function declarations found".into());
    }

    let mut generated = String::new();
    generated.push_str("// Auto-generated by build.rs. Do not edit manually.\n");
    generated.push_str("#[derive(OpenApi)]\n");
    generated.push_str("#[openapi(\n");
    generated.push_str("    info(\n");
    generated.push_str("        title = \"vz Runtime V2 API\",\n");
    generated.push_str("        version = \"2.0.0-alpha\",\n");
    generated.push_str("        description = API_DESCRIPTION\n");
    generated.push_str("    ),\n");
    generated.push_str("    paths(\n");
    for function in path_functions {
        generated.push_str("        ");
        generated.push_str(function.as_str());
        generated.push_str(",\n");
    }
    generated.push_str("    ),\n");
    generated.push_str("    components(schemas(\n");
    for schema in COMPONENT_SCHEMAS {
        generated.push_str("        ");
        generated.push_str(schema);
        generated.push_str(",\n");
    }
    generated.push_str("    ))\n");
    generated.push_str(")]\n");
    generated.push_str("struct ApiDoc;\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR")?);
    fs::write(out_dir.join("openapi_doc_generated.rs"), generated)?;
    Ok(())
}

fn parse_function_name(signature_line: &str) -> Option<&str> {
    let line = signature_line.strip_prefix("fn ")?;
    let name_end = line.find('(')?;
    Some(line[..name_end].trim())
}
